import { ServiceCategory, CustomerProfile, CaseScenario } from '../types';
import { media } from './media';

export const services: ServiceCategory[] = [
  {
    id: 'health',
    title: '回国体检与深度陪护',
    titleEn: 'Homecoming Health Checkup & Medical Escort',
    subtitle: '连接海外子女与国内父母的健康桥梁',
    subtitleEn: 'The health bridge connecting overseas children and domestic parents',
    description: '面向无法常伴父母身边的海外华人家庭，提供三甲医院绿色通道、定制体检方案、专业医护陪同、专车接送及双语报告解读。',
    descriptionEn: 'Designed for overseas Chinese families who cannot be with their parents. We coordinate priority hospital access, tailored checkup plans, clinical escort, private transfers, and bilingual report review.',
    image: media.images.medicalCare,
    features: [
      '全科医生协助定制体检方案，避免不必要的重复检查',
      '对接三甲医院及高端体检机构绿色通道，减少等待',
      '专业护士或医学背景人员全程一对一陪护',
      '提供中英双语报告解读，方便海外家庭理解结果',
      '异常指标可协助后续专科转诊及长期健康档案跟踪',
    ],
    featuresEn: [
      'Bespoke checkup plans reviewed by general practitioners',
      'Priority access at leading hospitals and premium checkup centers',
      'One-on-one medical companion with private transfers',
      'Professional bilingual medical reports for overseas families',
      'Specialist referral and long-term health record tracking',
    ],
    accentColor: 'from-[#002855] to-[#00529B]',
  },
  {
    id: 'travel',
    title: '高端定制家庭旅行',
    titleEn: 'Premium Bespoke Family Travel',
    subtitle: '为多代同堂设计的慢节奏安心旅程',
    subtitleEn: 'Stress-free luxury travel designed for multi-generational families',
    description: '为海外华人回国探亲、家族团聚或新西兰深度旅行定制慢节奏路线，兼顾老人、儿童和不同文化背景成员的节奏与兴趣。',
    descriptionEn: 'Tailor-made for diaspora families returning home, gathering across generations, or exploring New Zealand with comfort, privacy, and a calm pace.',
    image: media.images.familyTravel,
    features: [
      '每日节奏可控，兼顾老人休息与儿童兴趣',
      '一车一团独立成行，配备双语司导或管家',
      '精选高端酒店、私房菜及有文化深度的体验',
      '随车准备基础应急物资，并设置后勤响应机制',
      '行前线上沟通，按家庭成员偏好定制方案',
    ],
    featuresEn: [
      'Slow-paced schedules designed around family comfort',
      'Private vehicles with bilingual concierge support',
      'Handpicked hotels, private dining, and cultural experiences',
      'Basic emergency supplies and responsive operations backup',
      'Pre-trip consultation to tune every family preference',
    ],
    accentColor: 'from-[#00529B] to-[#00A4E4]',
  },
  {
    id: 'roots',
    title: '华裔新生代寻根与文化传承',
    titleEn: 'Next-Gen Roots-Seeking & Cultural Heritage',
    subtitle: '跨越山海，重新触摸家族来处',
    subtitleEn: 'Crossing mountains and seas to trace your lineage and origins',
    description: '联合地方文史资源，为华裔二代、三代及家庭开展祖籍线索梳理、宗祠拜访、非遗体验和影像记录，让文化记忆变成可感知的旅程。',
    descriptionEn: 'For second and third generation diaspora families, we coordinate archive research, ancestral visits, heritage workshops, and documentary-style records.',
    image: media.images.rootsSeeking,
    features: [
      '文史顾问协助梳理家族线索与迁徙脉络',
      '对接地方侨务资源、村委或宗亲会',
      '可安排寻根纪录片拍摄，记录团聚与祭祖时刻',
      '定制茶艺、书法、陶瓷、非遗工坊等体验',
      '为青少年设计更现代、更有参与感的文化交流',
    ],
    featuresEn: [
      'Lineage clues and migration routes reviewed by local researchers',
      'Liaison with local communities and clan representatives',
      'Optional documentary capture for reunions and ceremonies',
      'Private workshops in tea, calligraphy, ceramics, and heritage arts',
      'Modern cultural exchange designed for diaspora youth',
    ],
    accentColor: 'from-[#002855] to-[#B39D82]',
  },
];

export const customerProfiles: CustomerProfile[] = [
  {
    id: 'elite-professional',
    title: '海外资深职场精英与企业家',
    titleEn: 'Overseas Senior Professionals & Entrepreneurs',
    tag: '心系双亲',
    tagEn: 'Filial Devotion',
    quote: '人在海外，最担心的是父母需要帮助时，我无法第一时间站在他们身边。',
    quoteEn: 'My greatest concern overseas is not being there when my parents need help.',
    description: '工作繁忙、难以频繁回国，却希望用可靠、专业、可追踪的方式照顾父母健康的海外华人。',
    descriptionEn: 'Busy overseas professionals who need reliable, professional, and trackable support for parents at home.',
    painPoints: [
      '国内就医流程复杂，父母独自应对压力大',
      '时差导致沟通滞后，子女难以及时了解情况',
      '普通陪护缺乏医学背景和跨文化沟通能力',
    ],
    painPointsEn: [
      'Domestic medical workflows can overwhelm aging parents',
      'Time zones delay communication and decision-making',
      'Standard caretakers often lack clinical and cross-cultural skills',
    ],
    solutions: [
      '安排专业医护陪同及绿色通道预约',
      '提供双语报告和家庭线上说明会',
      '建立可持续更新的家庭健康档案',
    ],
    solutionsEn: [
      'Clinical escort and priority appointment coordination',
      'Bilingual reports and family review calls',
      'Long-term family health records',
    ],
  },
  {
    id: 'family-reunion',
    title: '注重亲情陪伴的华人家庭',
    titleEn: 'Diaspora Families Seeking Deep Connections',
    tag: '合家天伦',
    tagEn: 'Family Reunion',
    quote: '我们想要的不是赶景点，而是一家人真正舒服地在一起。',
    quoteEn: 'We do not want a rushed tour. We want time together that feels easy and meaningful.',
    description: '重视多代同堂体验、希望旅程舒适私密且不被购物安排打扰的家庭。',
    descriptionEn: 'Families seeking private, comfortable, multi-generational journeys without shopping pressure.',
    painPoints: [
      '传统团队节奏过快，不适合老人和孩子',
      '家庭成员年龄跨度大，饮食和作息难协调',
      '自由行筹备耗时，突发状况难处理',
    ],
    painPointsEn: [
      'Mass tours move too quickly for elders and children',
      'Different ages make meals and rest difficult to coordinate',
      'Independent planning is time-consuming and fragile',
    ],
    solutions: [
      '行前视频沟通，逐一确认家庭偏好',
      '安排舒适商务车和双语管家',
      '预留休息时间并配置后勤响应',
    ],
    solutionsEn: [
      'Pre-trip calls to understand every family member',
      'Comfortable private vehicles and bilingual concierge',
      'Flexible rest time and operations backup',
    ],
  },
  {
    id: 'identity-seeker',
    title: '华裔二代三代寻根家庭',
    titleEn: 'Heritage-Seeking Families & Diaspora Youth',
    tag: '文化寻根',
    tagEn: 'Identity Search',
    quote: '孩子未必会说流利中文，但他们应该知道自己从哪里来。',
    quoteEn: 'Our children may not speak fluent Chinese, but they should know where they come from.',
    description: '希望通过严谨、温暖、有仪式感的方式，让下一代重新理解家族记忆和文化身份。',
    descriptionEn: 'Families who want the next generation to connect with heritage through thoughtful and respectful experiences.',
    painPoints: [
      '祖籍线索零散，海外难以开展查证',
      '缺少地方资源，返乡容易无从下手',
      '传统文化活动容易说教，年轻人参与感弱',
    ],
    painPointsEn: [
      'Ancestral clues are scattered and hard to verify overseas',
      'Local connections are difficult to access',
      'Conventional heritage programs can feel distant to youth',
    ],
    solutions: [
      '协助梳理地名、族谱、照片和口述线索',
      '联络地方资源并设计返乡仪式',
      '结合影像记录与非遗体验提升参与感',
    ],
    solutionsEn: [
      'Review place names, family records, photos, and oral histories',
      'Coordinate local liaison and homecoming rituals',
      'Use documentary records and heritage workshops for engagement',
    ],
  },
];

export const caseScenarios: CaseScenario[] = [
  {
    id: 'case-1',
    image: media.images.medicalCare,
    title: '跨越九千公里的安心陪护',
    titleEn: 'Care Across 9,000 Kilometers',
    category: '体检陪护类',
    categoryEn: 'Medical Escort',
    client: '梁先生（奥克兰，软件架构师）',
    clientEn: 'Mr. Liang (Auckland, Software Architect)',
    location: '广州 & 深圳',
    story: '梁先生长期在奥克兰工作，母亲独居广州并有慢性病管理需求。WT 为其安排专业护士陪同体检、专车接送、双语报告解读，并在检查后组织线上说明，让海外家属及时了解指标变化与后续建议。',
    storyEn: 'Mr. Liang works in Auckland while his mother lives in Guangzhou with chronic health needs. WT coordinated clinical escort, private transfers, bilingual report review, and an online family briefing after the checkup.',
    highlight: '专业陪护让远在海外的子女也能清楚掌握父母健康状况。',
    highlightEn: 'Professional escort support helped an overseas child understand and manage a parent’s health from afar.',
    timeline: [
      { stage: '前期评估', stageEn: 'Pre-Assessment', desc: '收集病史、用药和既往检查资料。', descEn: 'Collected medical history, medication details, and prior records.' },
      { stage: '预约安排', stageEn: 'Scheduling', desc: '协调医院号源、检查顺序和接送时间。', descEn: 'Coordinated appointments, screening order, and transport timing.' },
      { stage: '现场陪护', stageEn: 'Escort Day', desc: '护士全程陪同完成检查并安抚老人情绪。', descEn: 'Nurse accompanied the parent through the complete screening flow.' },
      { stage: '报告交付', stageEn: 'Report Review', desc: '提供双语总结和家庭线上解读。', descEn: 'Delivered bilingual summary and online family review.' },
    ],
  },
  {
    id: 'case-2',
    image: media.images.familyTravel,
    title: '四代同堂的江南慢旅行',
    titleEn: 'A Slow Jiangnan Journey for Four Generations',
    category: '高端旅行类',
    categoryEn: 'Premium Travel',
    client: '陈女士（基督城，诊所创始人）',
    clientEn: 'Dr. Chen (Christchurch, Clinic Founder)',
    location: '上海 - 苏州 - 杭州',
    story: '陈女士希望带行动不便的父母和新西兰出生的孩子回国旅行。WT 将行程节奏降到舒适范围，安排商务车、无障碍动线、私密餐饮和文化体验，让每位家庭成员都能参与。',
    storyEn: 'Dr. Chen wanted to travel in China with elderly parents and New Zealand-born children. WT slowed the pace, arranged executive vehicles, accessibility routes, private dining, and cultural experiences.',
    highlight: '好的家庭旅行不是赶路，而是让每个人都被照顾到。',
    highlightEn: 'A great family journey is not about rushing. It is about making everyone feel considered.',
    timeline: [
      { stage: '家庭访谈', stageEn: 'Family Intake', desc: '确认老人行动能力、儿童兴趣和饮食偏好。', descEn: 'Reviewed mobility, children’s interests, and dining preferences.' },
      { stage: '路线设计', stageEn: 'Route Design', desc: '压缩每日移动时间并预留午休。', descEn: 'Reduced daily transit time and preserved rest windows.' },
      { stage: '现场执行', stageEn: 'Execution', desc: '管家按家庭状态动态调整参观顺序。', descEn: 'Concierge adjusted the sequence based on family energy.' },
      { stage: '影像留念', stageEn: 'Memory Archive', desc: '整理照片和旅行纪念册。', descEn: 'Prepared photo selections and a family travel keepsake.' },
    ],
  },
  {
    id: 'case-3',
    image: media.images.rootsSeeking,
    title: '从一张旧照片开始的寻根之旅',
    titleEn: 'A Roots Journey Started From One Old Photo',
    category: '文化寻根类',
    categoryEn: 'Roots-Seeking',
    client: '张教授（惠灵顿，高校教师）',
    clientEn: 'Prof. Zhang (Wellington, Academic)',
    location: '潮汕地区',
    story: '张教授只保留一张祖屋旧照和模糊地名。WT 协助梳理线索、联络地方文史资源，并安排宗祠拜访、家族访谈和非遗体验，让孩子第一次真实理解家族来处。',
    storyEn: 'Prof. Zhang only had an old ancestral-home photo and a vague place name. WT organized clue review, local liaison, ancestral hall visits, family interviews, and heritage workshops.',
    highlight: '寻根不是复古表演，而是一次认真面对家族记忆的旅程。',
    highlightEn: 'Roots-seeking is not nostalgia as performance. It is a serious encounter with family memory.',
    timeline: [
      { stage: '线索梳理', stageEn: 'Clue Review', desc: '整理照片、地名、口述信息和迁徙线索。', descEn: 'Reviewed photos, place names, oral clues, and migration hints.' },
      { stage: '地方联络', stageEn: 'Local Liaison', desc: '联系文史资源与宗亲代表。', descEn: 'Connected with local researchers and clan representatives.' },
      { stage: '返乡仪式', stageEn: 'Homecoming Visit', desc: '安排宗祠拜访、访谈和影像记录。', descEn: 'Arranged ancestral hall visit, interviews, and documentary capture.' },
      { stage: '文化延展', stageEn: 'Cultural Extension', desc: '为青少年安排非遗体验和双语讲解。', descEn: 'Hosted heritage workshops and bilingual context for youth.' },
    ],
  },
];

export const staticTranslations = {
  zh: {
    navServices: '核心业务',
    navCapabilities: '品牌实力',
    navClients: '服务群体',
    navWorkflow: '尊享流程',
    navCases: '真实见证',
    navContact: '预约咨询',
    ctaContactBtn: '预约1V1定制咨询',
    languageName: '简体中文',
    brandSlogan: '跨越山海 · 承托至亲 · 寻根神州',
    brandSubtitle: '专为海外华人打造的回国健康看护、高端定制旅行与华裔寻根传承平台',
    brandHeaderTitle: 'WT 新西兰文化交流与旅游有限公司',
    brandHeaderSub: 'NEW ZEALAND WT CULTURAL EXCHANGE & TOURISM LIMITED',
    heroTag: '新西兰注册机构 · 跨国尊享管家服务',
    startPlanning: '开始定制旅程 / 关怀计划',
    activeClients: '已服务海外家庭',
    satisfactionRate: '客户满意度',
    expertEscort: '专业医护团队',
    rootsVerified: '寻根档案梳理',
    plannerTitle: '智能方案配置器',
    plannerSubtitle: '快速匹配适合您家庭的专属服务构想',
    selectServiceType: '第一步：选择服务类型',
    selectUrgency: '第二步：期望开展时间',
    selectDestination: '第三步：目标省份 / 地区',
    additionalNeeds: '第四步：附加专属服务',
    generatePlan: '生成专属关怀 / 旅行方案构想',
    resetPlanner: '重新配置',
    plannerResultTitle: '您的 WT 尊享服务方案构想',
    parentInChina: '父母在国内',
    parentCareText: '我们将根据父母所在城市协调合适的医疗资源、专业陪护、专车接送和双语报告说明。',
    familyTravelText: '我们将为您的家庭定制慢节奏路线，兼顾老人、孩子和海外成员的语言、作息与兴趣。',
    rootsSeekingText: '我们将协助梳理祖籍线索，联络地方资源，并设计有仪式感和参与感的返乡寻根体验。',
    urgencyText1: '服务筹备组将在 <strong>48小时内</strong> 启动对接。',
    urgencyText2: '服务筹备组将配合您的假期，建议提前 <strong>3个月</strong> 开始规划。',
    submitInterest: '提交兴趣，联系顾问获取完整方案',
    submitting: '正在向新西兰总部递交...',
    submittedSuccess: '提交成功，我们将在24小时内与您联系。',
    capabilitiesTitle: '为什么海外华人信赖 WT？',
    capabilitiesSubtitle: '以国际化服务标准，承托万里之外的家人关怀与文化连接。',
    cap1Title: '新西兰注册机构保障',
    cap1Desc: '以透明协议、隐私保护和专业流程，为海外客户提供可靠的跨国服务体验。',
    cap2Title: '医疗与地方资源直连',
    cap2Desc: '对接国内医疗机构、地方侨务资源和文化顾问，提升安排效率和执行质量。',
    cap3Title: '双语医护与文史团队',
    cap3Desc: '服务人员覆盖医疗陪护、旅行管家和地方文化研究等专业背景。',
    clientsTitle: '我们服务的家庭',
    clientsSubtitle: '理解每份身在海外的牵挂，成全每次双向奔赴的亲情。',
    solutionLabel: 'WT 专属方案',
    painPointLabel: '核心困扰',
    featuresTitle: '核心业务板块详解',
    featuresSubtitle: '围绕健康、家庭旅行与文化寻根，提供可定制、可执行、可追踪的高端服务。',
    workflowTitle: 'WT 五星级全案定制流程',
    workflowSubtitle: '从新西兰到中国，我们全流程对齐您的期待。',
    step1: '海外沟通与需求建档',
    step1Desc: '通过线上会议收集健康、旅行或寻根需求，建立服务档案。',
    step2: '跨国方案定制',
    step2Desc: '由医疗顾问、旅行策划或文史顾问形成初步方案。',
    step3: '实地踏点与预对接',
    step3Desc: '预先核验医院、酒店、路线或地方联络资源。',
    step4: '白手套服务执行',
    step4Desc: '由国内团队按方案执行陪护、旅行或返乡活动。',
    step5: '报告交付与长期跟进',
    step5Desc: '交付双语报告、影像记录或寻根档案，并支持后续跟踪。',
    casesTitle: '真实家庭的故事',
    casesSubtitle: '每一次跨越山海的旅程，都是对家人的认真回应。',
    caseLocation: '涉及区域：',
    caseClient: '委托家庭：',
    caseShowTimeline: '查看 WT 白手套服务时间线',
    caseHideTimeline: '收起服务时间线',
    consultTitle: '尊享定制 · 开启咨询',
    consultSubtitle: '写下您对家人的牵挂，让我们为您整理可执行的跨国服务方案。',
    inputName: '您的姓名 / 称呼',
    inputEmail: '常用邮箱',
    inputPhone: '联系电话（请带国家区号）',
    inputWechat: '微信 / WhatsApp / Telegram',
    inputCategory: '感兴趣的服务领域',
    inputDetails: '详细需求描述',
    submitBtn: '提交给新西兰总部顾问团队',
    formNotice: '提交后，我们将在24小时内主动与您联系。',
    formSuccessTitle: '预约已收到 / Connection Established',
    formSuccessDesc: '感谢您对 WT 的信任。我们会安排资深项目顾问与您联系。',
  },
  en: {
    navServices: 'Pillars',
    navCapabilities: 'Strengths',
    navClients: 'Profiles',
    navWorkflow: 'Workflow',
    navCases: 'Stories',
    navContact: 'Inquiry',
    ctaContactBtn: 'Book 1-on-1 Consultation',
    languageName: 'English',
    brandSlogan: 'Connecting Generations · Caring Across Oceans · Tracing Chinese Roots',
    brandSubtitle: 'A platform for overseas Chinese families seeking premium health escort, bespoke family travel, and roots-seeking heritage services.',
    brandHeaderTitle: 'NEW ZEALAND WT CULTURAL EXCHANGE & TOURISM LIMITED',
    brandHeaderSub: 'WT New Zealand Cultural Exchange & Tourism Limited',
    heroTag: 'New Zealand Registered Entity · Transnational Concierge Service',
    startPlanning: 'Start Customizing Journey / Care Plan',
    activeClients: 'Diaspora Families Guided',
    satisfactionRate: 'Satisfaction Rating',
    expertEscort: 'Clinical Specialists',
    rootsVerified: 'Heritage Files Reviewed',
    plannerTitle: 'Intelligent Service Matcher',
    plannerSubtitle: 'Quickly visualize the right bespoke care or travel plan for your family',
    selectServiceType: 'Step 1: Choose Service Type',
    selectUrgency: 'Step 2: Desired Timeframe',
    selectDestination: 'Step 3: Target Province / Region',
    additionalNeeds: 'Step 4: Add-on Services',
    generatePlan: 'Generate Personalized Blueprint',
    resetPlanner: 'Reconfigure',
    plannerResultTitle: 'Your WT Bespoke Service Blueprint',
    parentInChina: 'Parents in China',
    parentCareText: 'We will coordinate medical resources, clinical escort, private transfers, and bilingual report review based on your parent’s city.',
    familyTravelText: 'We will design a slow-paced family route that balances elders, children, language needs, daily rhythms, and interests.',
    rootsSeekingText: 'We will help review ancestral clues, connect local resources, and design a meaningful homecoming experience.',
    urgencyText1: 'Our coordination desk will contact you within <strong>48 hours</strong>.',
    urgencyText2: 'For holiday travel, we recommend starting planning <strong>3 months</strong> in advance.',
    submitInterest: 'Transmit Interest to Advisor',
    submitting: 'Transmitting to New Zealand HQ...',
    submittedSuccess: 'Submitted successfully. We will contact you within 24 hours.',
    capabilitiesTitle: 'Why Global Diaspora Trust WT?',
    capabilitiesSubtitle: 'International service standards for family care and cultural connection across continents.',
    cap1Title: 'Registered NZ Compliance & Trust',
    cap1Desc: 'Transparent agreements, privacy protection, and professional workflows for reliable cross-border service.',
    cap2Title: 'Direct Medical & Local Liaison',
    cap2Desc: 'We coordinate medical facilities, local community resources, and cultural advisors for efficient execution.',
    cap3Title: 'Bilingual Clinical & Heritage Teams',
    cap3Desc: 'Our service network covers clinical escort, travel concierge, and local cultural research backgrounds.',
    clientsTitle: 'Who We Serve',
    clientsSubtitle: 'We understand the responsibility carried by families living far away.',
    solutionLabel: 'WT Bespoke Strategy',
    painPointLabel: 'Core Dilemma',
    featuresTitle: 'Core Service Portfolios',
    featuresSubtitle: 'Customizable, executable, and trackable premium services across health, travel, and roots-seeking.',
    workflowTitle: 'WT Five-Star Custom Journey',
    workflowSubtitle: 'From New Zealand to China, we align each stage with your expectations.',
    step1: 'Global Intake & Profile Creation',
    step1Desc: 'Online consultation to collect health, travel, or heritage needs.',
    step2: 'Cross-Border Blueprinting',
    step2Desc: 'Medical, travel, or heritage advisors draft the initial plan.',
    step3: 'Field Audit & Pre-Liaison',
    step3Desc: 'We verify hospitals, hotels, routes, or local contacts in advance.',
    step4: 'White-Glove Execution',
    step4Desc: 'The local team executes escort, travel, or homecoming activities.',
    step5: 'Handover & Long-Term Tracking',
    step5Desc: 'We deliver bilingual reports, media records, or heritage files with follow-up support.',
    casesTitle: 'Real Family Stories',
    casesSubtitle: 'Every journey across oceans is a serious response to family.',
    caseLocation: 'Region:',
    caseClient: 'Sponsor:',
    caseShowTimeline: 'Explore WT White-Glove Service Timeline',
    caseHideTimeline: 'Hide Service Timeline',
    consultTitle: 'Initiate Premium Consultation',
    consultSubtitle: 'Share your family needs and we will shape them into an executable cross-border service plan.',
    inputName: 'Your Full Name',
    inputEmail: 'Primary Email',
    inputPhone: 'Contact Phone with Country Code',
    inputWechat: 'WeChat / WhatsApp / Telegram',
    inputCategory: 'Service Category of Interest',
    inputDetails: 'Detailed Requirements',
    submitBtn: 'Submit to New Zealand HQ Advisor Team',
    formNotice: 'After submission, we will contact you within 24 hours.',
    formSuccessTitle: 'Connection Established',
    formSuccessDesc: 'Thank you for choosing WT. A senior project advisor will contact you shortly.',
  },
};

export const contactInfo = {
  nzRegistration: '#11783234',
  email: '1282380800@qq.com',
  wechatId: 'WT-NZ-CONCIERGE',
  aucklandPhone: '+64 (09) 889-1888',
  chinaPhone: '+86 (755) 8898-1212',
  aucklandAddress: 'Level 18, PwC Tower, 15 Customs Street West, Auckland 1010',
  chinaAddress: '深圳市福田区深南大道 2008 号中国凤凰大厦',
};

export const brandContent = {
  name: 'WT NEW ZEALAND',
  division: 'WT CULTURAL EXCHANGE',
  company: {
    zh: '新西兰文化交流与旅游有限公司',
    en: '& TOURISM LIMITED',
  },
  legalName: 'WT NEW ZEALAND CULTURAL EXCHANGE & TOURISM LIMITED',
};

export const headerContent = {
  registrationLabel: {
    zh: `新西兰商业注册认证 / NZ Registered Entity: ${contactInfo.nzRegistration}`,
    en: `NZ Registered Entity: ${contactInfo.nzRegistration}`,
  },
  phoneLabel: `${contactInfo.aucklandPhone} (Auckland HQ)`,
  languageToggleTitle: '切换语言 / Toggle Language',
  languageToggleLabel: {
    zh: 'EN',
    en: '繁 / 简',
  },
};

export const trustContent = {
  tags: [
    { zh: '安全守信', en: 'TRUST & LEGAL' },
    { zh: '官方直通', en: 'OFFICIAL LINK' },
    { zh: '学术医护', en: 'CLINICAL & SCHOLARLY' },
  ],
  eyebrow: {
    zh: '品牌硬实力',
    en: 'INSTITUTIONAL STRENGTH',
  },
  auditLabel: 'Class-A Audited',
};

export const audienceContent = {
  personaLabel: 'CLIENT PERSONA',
};

export const servicesContent = {
  eyebrow: {
    zh: '核心服务板块',
    en: 'CORE PORTFOLIOS',
  },
  sectionLabel: {
    zh: '板块',
    en: 'SECTION',
  },
  consultAction: {
    zh: '预约定制此专属方案',
    en: 'Consult on this portfolio',
  },
};

export const caseStoriesContent = {
  eyebrow: {
    zh: '真实案例场景',
    en: 'CASE SCENARIOS',
  },
  imageAlt: {
    zh: '案例场景配图',
    en: 'Case Scenario Illustration',
  },
  feedbackLabel: 'Verified Client Feedbacks',
  timelineJournalTitle: 'WT VIP WHITE-GLOVE DEPLOYMENT JOURNAL',
};

export const plannerContent = {
  defaultDestination: '广东 (Guangdong)',
  serviceTypes: [
    { id: 'health', label: { zh: '回国体检', en: 'Health' } },
    { id: 'travel', label: { zh: '家庭定制游', en: 'Travel' } },
    { id: 'roots', label: { zh: '文化寻根', en: 'Roots' } },
  ],
  urgencyOptions: [
    { id: 'fast', label: { zh: '近期急需 (48h内对接)', en: 'Immediate (Within 48h)' } },
    { id: 'plan', label: { zh: '规划未来 (配合假期)', en: 'Future Vacation Planner' } },
  ],
  destinationNote: {
    zh: '· 拒绝普通土特产代理',
    en: '· Pure Custom Service Only',
  },
  destinations: [
    { value: '广东 (Guangdong)', label: { zh: '广东 (珠三角及潮汕侨乡)', en: 'Guangdong Province' } },
    { value: '福建 (Fujian)', label: { zh: '福建 (闽南祖籍与岩茶文化源地)', en: 'Fujian Province' } },
    { value: '云南 (Yunnan)', label: { zh: '云南 (滇南高原与多民族非遗体验)', en: 'Yunnan Province' } },
    { value: '四川 (Sichuan)', label: { zh: '四川 (巴蜀山水与大熊猫保护科考)', en: 'Sichuan Province' } },
    { value: '新疆 (Xinjiang)', label: { zh: '新疆 (西域人文历史与壮丽丝路)', en: 'Xinjiang Region' } },
    { value: '青海 (Qinghai)', label: { zh: '青海 (高原净土生态与多代慢行)', en: 'Qinghai Province' } },
    { value: '浙江 (Zhejiang)', label: { zh: '浙江 (江南水乡与宗祠寻根)', en: 'Zhejiang Province' } },
    { value: '奥克兰 (Auckland)', label: { zh: '奥克兰总部 (新西兰纯净高奢定制)', en: 'Auckland (Pure Luxury Travel)' } },
  ],
  addons: [
    { id: 'bilingual', label: { zh: '中英双语顾问', en: 'Bilingual Advisor' }, resultLabel: { zh: '中英双语顾问', en: 'Bilingual Support' } },
    { id: 'medical', label: { zh: '1对1专业医护', en: 'Private Nurse Escort' }, resultLabel: { zh: '1对1专业医护', en: 'Clinical Nurse Escort' } },
    { id: 'documentary', label: { zh: '随行纪录片拍摄', en: 'Homecoming Film Crew' }, resultLabel: { zh: '随行纪录片', en: 'Custom Film Crew' } },
    { id: 'access', label: { zh: '轮椅/无障碍特检', en: 'Barrier-free Mapping' }, resultLabel: { zh: '无障碍查勘', en: 'Accessibility Mapping' } },
  ],
  calculating: {
    zh: '正在匹配专业团队...',
    en: 'Optimizing resources...',
  },
  confirmed: 'CONFIRMED',
  operationalSector: {
    zh: '目标服务区',
    en: 'OPERATIONAL SECTOR',
  },
  timelineStrategy: {
    zh: '时效响应',
    en: 'TIMELINE STRATEGY',
  },
  selectedPrivileges: {
    zh: '已选附加特权',
    en: 'EXCLUSIVE PRIVILEGES SELECTED',
  },
  checkSymbol: '✓',
  commitmentIcon: '⚠️',
  commitmentTitle: {
    zh: 'WT 纯净定制承诺 (WT Luxury Commitment)',
    en: 'WT LUXURY COMMITMENT',
  },
  commitmentText: {
    zh: '本公司专注于尊贵人文体验与医学陪护。我们不从事地方土特产品、伴手礼或普通代购百货代理。',
    en: 'We strictly focus on elite cultural custom tours and medical care. We do NOT trade, supply or procure mass-market local specialty products or souvenirs.',
  },
};

export const processContent = {
  eyebrow: {
    zh: '尊享定制流程',
    en: 'HOW IT WORKS',
  },
  qualityStandard: {
    zh: 'WT 白手套品质标准',
    en: 'WT ROYAL COMPLIANCE STEP',
  },
  milestoneHeading: {
    zh: '核心任务与成果交付物 :',
    en: 'CORE MILESTONES & OUTPUTS :',
  },
  checkSymbol: '✓',
  checklists: [
    {
      zh: ['注册海外专属管家账户', '专属Zoom视频需求分析会', '收集病历、行程偏好、寻根地名等'],
      en: ['Create global account', 'Dedicated Zoom video intake session', 'Consolidate medical, travel or clan records'],
    },
    {
      zh: ['全科顾问定制筛查表', '文史顾问梳理迁徙线索', '定制慢节奏路线草图'],
      en: ['GPs customize checkup schedules', 'Researchers analyze heritage clues', 'Slow itineraries and accessibility layouts drafted'],
    },
    {
      zh: ['预约医疗或地方资源', '实地核验酒店与动线', '确认地方联络人'],
      en: ['Reserve medical or local resources', 'Audit hotel and route accessibility', 'Confirm local liaison'],
    },
    {
      zh: ['专车点对点接送', '专业人员现场陪同', '重要时刻影像记录'],
      en: ['Point-to-point private transfers', 'Professional on-site escort', 'Media capture for important moments'],
    },
    {
      zh: ['交付双语总结', '整理影像与档案', '支持后续跟进'],
      en: ['Deliver bilingual summaries', 'Organize media and records', 'Support follow-up needs'],
    },
  ],
};

export const contactSectionContent = {
  eyebrow: {
    zh: '新西兰总部受托保障',
    en: 'NZ LAW COMPLIANT',
  },
  guarantees: [
    {
      title: { zh: '24小时极速响应', en: '24-Hour Active Response' },
      desc: { zh: '新西兰奥克兰总部与中国办事处无缝对接，首问责任制', en: 'Seamless dual coordination by Auckland HQ and domestic offices' },
    },
    {
      title: { zh: '1对1资深定制顾问', en: 'Personal Custom Director' },
      desc: { zh: '指派十年以上高端文旅或外事医疗背景项目总监提供服务', en: 'Senior project manager with 10+ years ex-diplomatic or medical consulting experience' },
    },
    {
      title: { zh: '保密协议(NDA)护航', en: 'High-Spec Privacy Compliance' },
      desc: { zh: '严格遵守新西兰信息法及NDA，对家庭成员隐私进行保护', en: 'Compliant with NZ Information Act and NDA expectations for family details' },
    },
  ],
  placeholders: {
    name: { zh: '例如：张先生', en: 'e.g., Prof. Zhang' },
    messenger: 'WeChat ID / WhatsApp / Telegram',
    email: 'name@domain.com',
    phone: '+64 21 000 0000',
    details: {
      zh: '例：我定居在奥克兰，父母在广州天河区。希望预约三甲医院体检，需要双语报告，预计今年10月回国探亲...',
      en: 'e.g., Based in Wellington, parents in Hangzhou. Seeking medical checkups with custom mobility mapping...',
    },
  },
  categories: [
    { value: 'health', label: { zh: '回国深度体检与医院绿色通道陪护', en: 'Homecoming Health Checkup & Escort' } },
    { value: 'travel', label: { zh: '多代同堂高端定制慢旅行', en: 'Custom Multi-Generational Travel' } },
    { value: 'roots', label: { zh: '华裔新生代谱系考证与返乡寻根', en: 'Roots-Seeking & Ancestral Heritage Search' } },
    { value: 'multi', label: { zh: '多项联合定制服务规划', en: 'Comprehensive Joint Custom Portfolios' } },
  ],
  successMeta: {
    ticketId: { zh: '受理号', en: 'TICKET ID' },
    intakeZone: { zh: '时区归属', en: 'INTAKE ZONE' },
    intakeValue: 'Auckland / Wellington',
    securityLine: {
      zh: '安全加密连接 · 新西兰信息安全标准',
      en: 'SECURE SSL PIPELINE · COMPLIANT WITH APY-ACT',
    },
  },
};

export const footerContent = {
  brandDescription: {
    zh: '新西兰注册公司：WT NEW ZEALAND CULTURAL EXCHANGE & TOURISM LIMITED，致力于架设连接全球华裔家庭与中国文化、健康及旅行资源的信任桥梁。',
    en: 'Registered in NZ: WT NEW ZEALAND CULTURAL EXCHANGE & TOURISM LIMITED. Dedicated to bridging diaspora families with trusted care, travel, and cultural resources.',
  },
  certification: 'NZ TOURISM CERTIFIED',
  directoryTitle: {
    zh: '服务地图',
    en: 'DIRECTORY',
  },
  hubsTitle: {
    zh: '全球接待中心与联络方式',
    en: 'GLOBAL HUBS & CONTACT',
  },
  aucklandHub: {
    zh: '奥克兰总部 (HQ)',
    en: 'Auckland HQ',
  },
  chinaHub: {
    zh: '中国南方办事处',
    en: 'Southern China Hub',
  },
  emailLabel: {
    zh: '客服邮箱：',
    en: 'Email: ',
  },
  wechatLabel: {
    zh: '微信号：',
    en: 'WeChat ID: ',
  },
  copyrightNotice: {
    zh: `版权所有：WT 新西兰文化交流与旅游有限公司 | 新西兰注册号：${contactInfo.nzRegistration} | 粤ICP备 8910234号-1`,
    en: `NZ Registration No: ${contactInfo.nzRegistration} | Privacy & NDA Compliances Certified by NZ-Gvt Guidelines.`,
  },
  ndaTerms: {
    zh: '保密协议条款',
    en: 'NDA Terms',
  },
  medicalDisclaimer: {
    zh: '医疗免责声明',
    en: 'Medical Disclaimer',
  },
};

export const wechatContactContent = {
  title: {
    zh: '微信扫码 · 即刻对接',
    en: 'WECHAT OFFICIAL CHAT',
  },
  scanLabel: {
    zh: '扫二维码，添加我为朋友',
    en: 'Scan to Add Me as Friend',
  },
  wechatIdLabel: {
    zh: `微信客服号：${contactInfo.wechatId}`,
    en: `WeChat ID: ${contactInfo.wechatId}`,
  },
  emailHeading: {
    zh: '官方联系人邮箱',
    en: 'CONTACT EMAIL',
  },
  copyTitle: 'Copy Email',
  copied: {
    zh: '已复制',
    en: 'COPIED',
  },
  copy: {
    zh: '复制',
    en: 'COPY',
  },
  aucklandPhoneLabel: {
    zh: '新西兰奥克兰总部',
    en: 'Auckland HQ Phone',
  },
  chinaPhoneLabel: {
    zh: '中国南方办事处',
    en: 'China Hub Phone',
  },
};
