import { ServiceCategory, CustomerProfile, CaseScenario } from '../types';
import { media } from './media';

export const services: ServiceCategory[] = [
  {
    id: 'health',
    title: '回国体检陪同与行程协助',
    titleEn: 'Homecoming Checkup Companion & Travel Assistance',
    subtitle: '为海外家庭安排更安心的回国陪同服务',
    subtitleEn: 'Practical companion support for overseas families returning home',
    description: '面向无法常伴父母身边的海外华人家庭，协助安排体检预约、行程接送、现场陪同、语言沟通、资料整理及家属信息同步。WT 提供服务与旅行协调，不提供诊断、治疗建议或医疗结果承诺。',
    descriptionEn: 'For overseas Chinese families who cannot be with their parents, we assist with checkup scheduling, transfers, on-site companionship, language support, document organization, and family updates. WT provides service and travel coordination, not diagnosis, treatment advice, or medical outcome guarantees.',
    image: media.images.medicalCare,
    features: [
      '协助整理体检需求、既往资料和预约信息',
      '陪同前往体检机构或医院，并协助现场流程沟通',
      '安排专车接送、适老化动线和必要的行程缓冲',
      '协助翻译、整理和转交体检报告，方便海外家属查看',
      '如需进一步咨询，可协助联系持牌医疗机构或医生，由专业人员作出判断',
    ],
    featuresEn: [
      'Help organize checkup needs, past documents, and appointment details',
      'Companion support for visits to checkup centers or hospitals',
      'Private transfers, senior-friendly routing, and practical schedule buffers',
      'Assistance translating, organizing, and forwarding checkup reports',
      'If further consultation is needed, we can help contact licensed providers for their professional judgment',
    ],
    accentColor: 'from-[#002855] to-[#00529B]',
  },
  {
    id: 'travel',
    title: '高端定制家庭旅行',
    titleEn: 'Premium Bespoke Family Travel',
    subtitle: '为多代同堂设计的慢节奏安心旅程',
    subtitleEn: 'Stress-free luxury travel designed for multi-generational families',
    description: '为海外华人回国探亲、家族团聚或新西兰深度旅行定制慢节奏路线，兼顾老人、儿童和不同文化背景成员的节奏与兴趣。',
    descriptionEn: 'Tailor-made for diaspora families returning home, gathering across generations, or exploring New Zealand with comfort, privacy, and a calm pace.',
    image: media.images.familyTravel,
    features: [
      '每日节奏可控，兼顾老人休息与儿童兴趣',
      '一车一团独立成行，配备双语司导或管家',
      '精选高端酒店、私房菜及有文化深度的体验',
      '随车准备基础应急物资，并设置后勤响应机制',
      '行前线上沟通，按家庭成员偏好定制方案',
    ],
    featuresEn: [
      'Slow-paced schedules designed around family comfort',
      'Private vehicles with bilingual concierge support',
      'Handpicked hotels, private dining, and cultural experiences',
      'Basic emergency supplies and responsive operations backup',
      'Pre-trip consultation to tune every family preference',
    ],
    accentColor: 'from-[#00529B] to-[#00A4E4]',
  },
  {
    id: 'roots',
    title: '华裔新生代寻根与文化传承',
    titleEn: 'Next-Gen Roots-Seeking & Cultural Heritage',
    subtitle: '跨越山海，重新触摸家族来处',
    subtitleEn: 'Crossing mountains and seas to trace your lineage and origins',
    description: '联合地方文史资源，为华裔二代、三代及家庭开展祖籍线索梳理、宗祠拜访、非遗体验和影像记录，让文化记忆变成可感知的旅程。',
    descriptionEn: 'For second and third generation diaspora families, we coordinate archive research, ancestral visits, heritage workshops, and documentary-style records.',
    image: media.images.rootsSeeking,
    features: [
      '文史顾问协助梳理家族线索与迁徙脉络',
      '对接地方侨务资源、村委或宗亲会',
      '可安排寻根纪录片拍摄，记录团聚与祭祖时刻',
      '定制茶艺、书法、陶瓷、非遗工坊等体验',
      '为青少年设计更现代、更有参与感的文化交流',
    ],
    featuresEn: [
      'Lineage clues and migration routes reviewed by local researchers',
      'Liaison with local communities and clan representatives',
      'Optional documentary capture for reunions and ceremonies',
      'Private workshops in tea, calligraphy, ceramics, and heritage arts',
      'Modern cultural exchange designed for diaspora youth',
    ],
    accentColor: 'from-[#002855] to-[#B39D82]',
  },
];

export const customerProfiles: CustomerProfile[] = [
  {
    id: 'elite-professional',
    title: '海外资深职场人士与企业家',
    titleEn: 'Overseas Senior Professionals & Entrepreneurs',
    tag: '心系双亲',
    tagEn: 'Filial Devotion',
    quote: '人在海外，最担心的是父母需要陪同办事或体检时，我无法第一时间站在他们身边。',
    quoteEn: 'My greatest concern overseas is not being there when my parents need help with appointments or travel.',
    description: '工作繁忙、难以频繁回国，却希望用可靠、清晰、可追踪的方式协助父母完成体检、出行与资料沟通的海外华人。',
    descriptionEn: 'Busy overseas professionals who need reliable, clear, and trackable support for parents completing checkups, travel, and document communication.',
    painPoints: [
      '国内预约、交通和现场流程复杂，父母独自处理压力大',
      '时差导致沟通滞后，子女难以及时了解行程进展',
      '普通陪同缺乏双语沟通能力和细致的家庭服务意识',
    ],
    painPointsEn: [
      'Appointments, transport, and on-site processes can overwhelm aging parents',
      'Time zones delay communication and decision-making',
      'Standard companion support often lacks bilingual and family-service awareness',
    ],
    solutions: [
      '协助预约、接送、陪同和现场沟通',
      '整理双语资料摘要并同步给海外家属',
      '建立服务记录，方便后续家庭沟通与行程跟进',
    ],
    solutionsEn: [
      'Appointment, transfer, companion, and on-site communication support',
      'Bilingual document summaries for overseas family members',
      'Service records for future family communication and follow-up',
    ],
  },
  {
    id: 'family-reunion',
    title: '注重亲情陪伴的华人家庭',
    titleEn: 'Diaspora Families Seeking Deep Connections',
    tag: '合家天伦',
    tagEn: 'Family Reunion',
    quote: '我们想要的不是赶景点，而是一家人真正舒服地在一起。',
    quoteEn: 'We do not want a rushed tour. We want time together that feels easy and meaningful.',
    description: '重视多代同堂体验、希望旅程舒适私密且不被购物安排打扰的家庭。',
    descriptionEn: 'Families seeking private, comfortable, multi-generational journeys without shopping pressure.',
    painPoints: [
      '传统团队节奏过快，不适合老人和孩子',
      '家庭成员年龄跨度大，饮食和作息难协调',
      '自由行筹备耗时，突发状况难处理',
    ],
    painPointsEn: [
      'Mass tours move too quickly for elders and children',
      'Different ages make meals and rest difficult to coordinate',
      'Independent planning is time-consuming and fragile',
    ],
    solutions: [
      '行前视频沟通，逐一确认家庭偏好',
      '安排舒适商务车和双语管家',
      '预留休息时间并配置后勤响应',
    ],
    solutionsEn: [
      'Pre-trip calls to understand every family member',
      'Comfortable private vehicles and bilingual concierge',
      'Flexible rest time and operations backup',
    ],
  },
  {
    id: 'identity-seeker',
    title: '华裔二代三代寻根家庭',
    titleEn: 'Heritage-Seeking Families & Diaspora Youth',
    tag: '文化寻根',
    tagEn: 'Identity Search',
    quote: '孩子未必会说流利中文，但他们应该知道自己从哪里来。',
    quoteEn: 'Our children may not speak fluent Chinese, but they should know where they come from.',
    description: '希望通过严谨、温暖、有仪式感的方式，让下一代重新理解家族记忆和文化身份。',
    descriptionEn: 'Families who want the next generation to connect with heritage through thoughtful and respectful experiences.',
    painPoints: [
      '祖籍线索零散，海外难以开展查证',
      '缺少地方资源，返乡容易无从下手',
      '传统文化活动容易说教，年轻人参与感弱',
    ],
    painPointsEn: [
      'Ancestral clues are scattered and hard to verify overseas',
      'Local connections are difficult to access',
      'Conventional heritage programs can feel distant to youth',
    ],
    solutions: [
      '协助梳理地名、族谱、照片和口述线索',
      '联络地方资源并设计返乡仪式',
      '结合影像记录与非遗体验提升参与感',
    ],
    solutionsEn: [
      'Review place names, family records, photos, and oral histories',
      'Coordinate local liaison and homecoming rituals',
      'Use documentary records and heritage workshops for engagement',
    ],
  },
];

export const caseScenarios: CaseScenario[] = [
  {
    id: 'case-1',
    image: media.images.medicalCare,
    title: '跨越九千公里的安心陪同',
    titleEn: 'Companion Support Across 9,000 Kilometers',
    category: '体检陪同类',
    categoryEn: 'Checkup Companion',
    client: '梁先生（奥克兰，软件架构师）',
    clientEn: 'Mr. Liang (Auckland, Software Architect)',
    location: '广州 & 深圳',
    story: '梁先生长期在奥克兰工作，母亲独居广州，需要有人协助完成体检预约、当天交通、现场沟通和资料转交。WT 安排行程陪同人员协助接送、引导流程、整理资料，并在检查后把报告和注意事项同步给海外家属。医学判断由持牌医疗机构及医生负责。',
    storyEn: 'Mr. Liang works in Auckland while his mother lives in Guangzhou. She needed help with checkup scheduling, same-day transport, on-site communication, and document handover. WT arranged companion support for transfers, process guidance, document organization, and family updates. Medical judgment remained with licensed providers.',
    highlight: '我们解决的是陪同、沟通和行程协调，让远在海外的家人更清楚、更安心。',
    highlightEn: 'We solve companionship, communication, and travel coordination so overseas families feel clearer and more at ease.',
    timeline: [
      { stage: '需求整理', stageEn: 'Needs Review', desc: '整理体检需求、出行限制、联系人和既往资料。', descEn: 'Organized checkup needs, mobility limits, contacts, and past documents.' },
      { stage: '预约与接送', stageEn: 'Scheduling & Transfer', desc: '协助确认预约、交通时间和现场集合方式。', descEn: 'Helped confirm appointments, transport timing, and meeting details.' },
      { stage: '现场陪同', stageEn: 'On-site Companion', desc: '陪同完成现场流程，并协助语言沟通和资料递交。', descEn: 'Provided on-site companion support, language help, and document handover.' },
      { stage: '资料同步', stageEn: 'Family Update', desc: '整理报告、票据和说明，转交海外家属查看。', descEn: 'Organized reports, receipts, and notes for overseas family review.' },
    ],
  },
  {
    id: 'case-2',
    image: media.images.familyTravel,
    title: '四代同堂的江南慢旅行',
    titleEn: 'A Slow Jiangnan Journey for Four Generations',
    category: '高端旅行类',
    categoryEn: 'Premium Travel',
    client: '陈女士（基督城，诊所创始人）',
    clientEn: 'Dr. Chen (Christchurch, Clinic Founder)',
    location: '上海 - 苏州 - 杭州',
    story: '陈女士希望带行动不便的父母和新西兰出生的孩子回国旅行。WT 将行程节奏降到舒适范围，安排商务车、无障碍动线、私密餐饮和文化体验，让每位家庭成员都能参与。',
    storyEn: 'Dr. Chen wanted to travel in China with elderly parents and New Zealand-born children. WT slowed the pace, arranged executive vehicles, accessibility routes, private dining, and cultural experiences.',
    highlight: '好的家庭旅行不是赶路，而是让每个人都被照顾到。',
    highlightEn: 'A great family journey is not about rushing. It is about making everyone feel considered.',
    timeline: [
      { stage: '家庭访谈', stageEn: 'Family Intake', desc: '确认老人行动能力、儿童兴趣和饮食偏好。', descEn: 'Reviewed mobility, children’s interests, and dining preferences.' },
      { stage: '路线设计', stageEn: 'Route Design', desc: '压缩每日移动时间并预留午休。', descEn: 'Reduced daily transit time and preserved rest windows.' },
      { stage: '现场执行', stageEn: 'Execution', desc: '管家按家庭状态动态调整参观顺序。', descEn: 'Concierge adjusted the sequence based on family energy.' },
      { stage: '影像留念', stageEn: 'Memory Archive', desc: '整理照片和旅行纪念册。', descEn: 'Prepared photo selections and a family travel keepsake.' },
    ],
  },
  {
    id: 'case-3',
    image: media.images.rootsSeeking,
    title: '从一张旧照片开始的寻根之旅',
    titleEn: 'A Roots Journey Started From One Old Photo',
    category: '文化寻根类',
    categoryEn: 'Roots-Seeking',
    client: '张教授（惠灵顿，高校教师）',
    clientEn: 'Prof. Zhang (Wellington, Academic)',
    location: '潮汕地区',
    story: '张教授只保留一张祖屋旧照和模糊地名。WT 协助梳理线索、联络地方文史资源，并安排宗祠拜访、家族访谈和非遗体验，让孩子第一次真实理解家族来处。',
    storyEn: 'Prof. Zhang only had an old ancestral-home photo and a vague place name. WT organized clue review, local liaison, ancestral hall visits, family interviews, and heritage workshops.',
    highlight: '寻根不是复古表演，而是一次认真面对家族记忆的旅程。',
    highlightEn: 'Roots-seeking is not nostalgia as performance. It is a serious encounter with family memory.',
    timeline: [
      { stage: '线索梳理', stageEn: 'Clue Review', desc: '整理照片、地名、口述信息和迁徙线索。', descEn: 'Reviewed photos, place names, oral clues, and migration hints.' },
      { stage: '地方联络', stageEn: 'Local Liaison', desc: '联系文史资源与宗亲代表。', descEn: 'Connected with local researchers and clan representatives.' },
      { stage: '返乡仪式', stageEn: 'Homecoming Visit', desc: '安排宗祠拜访、访谈和影像记录。', descEn: 'Arranged ancestral hall visit, interviews, and documentary capture.' },
      { stage: '文化延展', stageEn: 'Cultural Extension', desc: '为青少年安排非遗体验和双语讲解。', descEn: 'Hosted heritage workshops and bilingual context for youth.' },
    ],
  },
];

export const staticTranslations = {
  zh: {
    navServices: '核心业务',
    navProduct: '产品介绍',
    navCapabilities: '品牌实力',
    navClients: '服务群体',
    navWorkflow: '尊享流程',
    navCases: '真实见证',
    navContact: '预约咨询',
    ctaContactBtn: '预约1V1定制咨询',
    languageName: '简体中文',
    brandSlogan: '跨越山海 · 承托至亲 · 寻根神州',
    brandSubtitle: '专为海外华人家庭打造的回国陪同、定制旅行与文化寻根服务平台',
    brandHeaderTitle: 'WT 新西兰文化交流与旅游有限公司',
    brandHeaderSub: 'NEW ZEALAND WT CULTURAL EXCHANGE & TOURISM LIMITED',
    heroTag: '新西兰注册机构 · 跨国旅行与家庭协助服务',
    startPlanning: '开始定制旅程 / 陪同计划',
    activeClients: '已服务海外家庭',
    satisfactionRate: '客户满意度',
    expertEscort: '双语服务团队',
    rootsVerified: '寻根档案梳理',
    plannerTitle: '智能方案配置器',
    plannerSubtitle: '快速匹配适合您家庭的专属服务构想',
    selectServiceType: '第一步：选择服务类型',
    selectUrgency: '第二步：期望开展时间',
    selectDestination: '第三步：目标省份 / 地区',
    additionalNeeds: '第四步：附加专属服务',
    generatePlan: '生成专属陪同 / 旅行方案构想',
    resetPlanner: '重新配置',
    plannerResultTitle: '您的 WT 尊享服务方案构想',
    parentInChina: '父母在国内',
    parentCareText: '我们将根据父母所在城市协助安排体检预约、行程接送、现场陪同、语言沟通和资料整理。',
    familyTravelText: '我们将为您的家庭定制慢节奏路线，兼顾老人、孩子和海外成员的语言、作息与兴趣。',
    rootsSeekingText: '我们将协助梳理祖籍线索，联络地方资源，并设计有仪式感和参与感的返乡寻根体验。',
    urgencyText1: '服务筹备组将在 <strong>48小时内</strong> 启动对接。',
    urgencyText2: '服务筹备组将配合您的假期，建议提前 <strong>3个月</strong> 开始规划。',
    submitInterest: '提交兴趣，联系顾问获取完整方案',
    submitting: '正在向新西兰总部递交...',
    submittedSuccess: '提交成功，我们将在24小时内与您联系。',
    capabilitiesTitle: '为什么海外华人信赖 WT？',
    capabilitiesSubtitle: '以国际化服务标准，承托万里之外的家人陪同、旅行安排与文化连接。',
    cap1Title: '新西兰注册机构保障',
    cap1Desc: '以透明协议、隐私保护和专业流程，为海外客户提供可靠的跨国服务体验。',
    cap2Title: '旅行与本地资源协调',
    cap2Desc: '对接交通、住宿、翻译沟通、地方接待与文化顾问资源，提升安排效率和执行质量。',
    cap3Title: '双语管家与文史团队',
    cap3Desc: '服务人员覆盖旅行管家、双语沟通、现场陪同和地方文化研究等背景。',
    clientsTitle: '我们服务的家庭',
    clientsSubtitle: '理解每份身在海外的牵挂，成全每次双向奔赴的亲情。',
    solutionLabel: 'WT 专属方案',
    painPointLabel: '核心困扰',
    featuresTitle: '核心业务板块详解',
    featuresSubtitle: '围绕回国陪同、家庭旅行与文化寻根，提供可定制、可执行、可追踪的高端服务。',
    workflowTitle: 'WT 五星级全案定制流程',
    workflowSubtitle: '从新西兰到中国，我们全流程对齐您的期待。',
    step1: '海外沟通与需求建档',
    step1Desc: '通过线上会议收集陪同、旅行或寻根需求，建立服务档案。',
    step2: '跨国方案定制',
    step2Desc: '由旅行策划、服务管家或文史顾问形成初步方案。',
    step3: '实地踏点与预对接',
    step3Desc: '预先核验交通、住宿、路线、预约信息或地方联络资源。',
    step4: '白手套服务执行',
    step4Desc: '由国内团队按方案执行陪同、旅行或返乡活动。',
    step5: '资料交付与后续跟进',
    step5Desc: '交付行程记录、双语资料、影像记录或寻根档案，并支持后续沟通。',
    casesTitle: '真实家庭的故事',
    casesSubtitle: '每一次跨越山海的旅程，都是对家人的认真回应。',
    caseLocation: '涉及区域：',
    caseClient: '委托家庭：',
    caseShowTimeline: '查看 WT 白手套服务时间线',
    caseHideTimeline: '收起服务时间线',
    consultTitle: '尊享定制 · 开启咨询',
    consultSubtitle: '写下您对家人的牵挂，让我们为您整理可执行的跨国服务方案。',
    inputName: '您的姓名 / 称呼',
    inputEmail: '常用邮箱',
    inputPhone: '联系电话（请带国家区号）',
    inputWechat: '微信 / WhatsApp / Telegram',
    inputCategory: '感兴趣的服务领域',
    inputDetails: '详细需求描述',
    submitBtn: '提交给新西兰总部顾问团队',
    formNotice: '提交后，我们将在24小时内主动与您联系。',
    formSuccessTitle: '预约已收到 / Connection Established',
    formSuccessDesc: '感谢您对 WT 的信任。我们会安排资深项目顾问与您联系。',
  },
  en: {
    navServices: 'Pillars',
    navProduct: 'Product',
    navCapabilities: 'Strengths',
    navClients: 'Profiles',
    navWorkflow: 'Workflow',
    navCases: 'Stories',
    navContact: 'Inquiry',
    ctaContactBtn: 'Book 1-on-1 Consultation',
    languageName: 'English',
    brandSlogan: 'Connecting Generations · Caring Across Oceans · Tracing Chinese Roots',
    brandSubtitle: 'A service platform for overseas Chinese families seeking homecoming companion support, bespoke family travel, and roots-seeking heritage journeys.',
    brandHeaderTitle: 'NEW ZEALAND WT CULTURAL EXCHANGE & TOURISM LIMITED',
    brandHeaderSub: 'WT New Zealand Cultural Exchange & Tourism Limited',
    heroTag: 'New Zealand Registered Entity · Cross-Border Travel & Family Assistance',
    startPlanning: 'Start Customizing Journey / Companion Plan',
    activeClients: 'Diaspora Families Guided',
    satisfactionRate: 'Satisfaction Rating',
    expertEscort: 'Bilingual Service Team',
    rootsVerified: 'Heritage Files Reviewed',
    plannerTitle: 'Intelligent Service Matcher',
    plannerSubtitle: 'Quickly visualize the right bespoke companion or travel plan for your family',
    selectServiceType: 'Step 1: Choose Service Type',
    selectUrgency: 'Step 2: Desired Timeframe',
    selectDestination: 'Step 3: Target Province / Region',
    additionalNeeds: 'Step 4: Add-on Services',
    generatePlan: 'Generate Personalized Blueprint',
    resetPlanner: 'Reconfigure',
    plannerResultTitle: 'Your WT Bespoke Service Blueprint',
    parentInChina: 'Parents in China',
    parentCareText: 'We will assist with checkup scheduling, transfers, on-site companionship, language support, and document organization based on your parent’s city.',
    familyTravelText: 'We will design a slow-paced family route that balances elders, children, language needs, daily rhythms, and interests.',
    rootsSeekingText: 'We will help review ancestral clues, connect local resources, and design a meaningful homecoming experience.',
    urgencyText1: 'Our coordination desk will contact you within <strong>48 hours</strong>.',
    urgencyText2: 'For holiday travel, we recommend starting planning <strong>3 months</strong> in advance.',
    submitInterest: 'Transmit Interest to Advisor',
    submitting: 'Transmitting to New Zealand HQ...',
    submittedSuccess: 'Submitted successfully. We will contact you within 24 hours.',
    capabilitiesTitle: 'Why Global Diaspora Trust WT?',
    capabilitiesSubtitle: 'International service standards for family companionship, travel planning, and cultural connection across continents.',
    cap1Title: 'Registered NZ Compliance & Trust',
    cap1Desc: 'Transparent agreements, privacy protection, and professional workflows for reliable cross-border service.',
    cap2Title: 'Travel & Local Resource Coordination',
    cap2Desc: 'We coordinate transport, accommodation, language support, local reception, and cultural advisor resources for efficient execution.',
    cap3Title: 'Bilingual Concierge & Heritage Teams',
    cap3Desc: 'Our service network covers travel concierge, bilingual communication, on-site companion support, and local cultural research.',
    clientsTitle: 'Who We Serve',
    clientsSubtitle: 'We understand the responsibility carried by families living far away.',
    solutionLabel: 'WT Bespoke Strategy',
    painPointLabel: 'Core Dilemma',
    featuresTitle: 'Core Service Portfolios',
    featuresSubtitle: 'Customizable, executable, and trackable premium services across companion support, family travel, and roots-seeking.',
    workflowTitle: 'WT Five-Star Custom Journey',
    workflowSubtitle: 'From New Zealand to China, we align each stage with your expectations.',
    step1: 'Global Intake & Profile Creation',
    step1Desc: 'Online consultation to collect companion, travel, or heritage needs.',
    step2: 'Cross-Border Blueprinting',
    step2Desc: 'Travel planners, service concierges, or heritage advisors draft the initial plan.',
    step3: 'Field Audit & Pre-Liaison',
    step3Desc: 'We verify transport, hotels, routes, appointment details, or local contacts in advance.',
    step4: 'White-Glove Execution',
    step4Desc: 'The local team executes companion support, travel, or homecoming activities.',
    step5: 'Handover & Follow-Up',
    step5Desc: 'We deliver itinerary records, bilingual documents, media records, or heritage files with follow-up support.',
    casesTitle: 'Real Family Stories',
    casesSubtitle: 'Every journey across oceans is a serious response to family.',
    caseLocation: 'Region:',
    caseClient: 'Sponsor:',
    caseShowTimeline: 'Explore WT White-Glove Service Timeline',
    caseHideTimeline: 'Hide Service Timeline',
    consultTitle: 'Initiate Premium Consultation',
    consultSubtitle: 'Share your family needs and we will shape them into an executable cross-border service plan.',
    inputName: 'Your Full Name',
    inputEmail: 'Primary Email',
    inputPhone: 'Contact Phone with Country Code',
    inputWechat: 'WeChat / WhatsApp / Telegram',
    inputCategory: 'Service Category of Interest',
    inputDetails: 'Detailed Requirements',
    submitBtn: 'Submit to New Zealand HQ Advisor Team',
    formNotice: 'After submission, we will contact you within 24 hours.',
    formSuccessTitle: 'Connection Established',
    formSuccessDesc: 'Thank you for choosing WT. A senior project advisor will contact you shortly.',
  },
};

export const contactInfo = {
  nzRegistration: '#11783234',
  email: '1282380800@qq.com',
  wechatId: 'WT-NZ-CONCIERGE',
  aucklandPhone: '+64 (09) 889-1888',
  chinaPhone: '+86 (755) 8898-1212',
};

export const brandContent = {
  name: 'WT NEW ZEALAND',
  division: 'WT CULTURAL EXCHANGE',
  company: {
    zh: '新西兰文化交流与旅游有限公司',
    en: '& TOURISM LIMITED',
  },
  legalName: 'WT NEW ZEALAND CULTURAL EXCHANGE & TOURISM LIMITED',
};

export const headerContent = {
  registrationLabel: {
    zh: `新西兰商业注册认证 / NZ Registered Entity: ${contactInfo.nzRegistration}`,
    en: `NZ Registered Entity: ${contactInfo.nzRegistration}`,
  },
  phoneLabel: `${contactInfo.aucklandPhone} (Auckland HQ)`,
  languageToggleTitle: '切换语言 / Toggle Language',
  languageToggleLabel: {
    zh: 'EN',
    en: '繁 / 简',
  },
};

export const trustContent = {
  tags: [
    { zh: '安全守信', en: 'TRUST & LEGAL' },
    { zh: '资源协调', en: 'COORDINATION' },
    { zh: '双语服务', en: 'BILINGUAL SERVICE' },
  ],
  eyebrow: {
    zh: '品牌硬实力',
    en: 'INSTITUTIONAL STRENGTH',
  },
  auditLabel: 'Service Standard',
};

export const audienceContent = {
  personaLabel: 'CLIENT PERSONA',
};

export const servicesContent = {
  eyebrow: {
    zh: '核心服务板块',
    en: 'CORE PORTFOLIOS',
  },
  sectionLabel: {
    zh: '板块',
    en: 'SECTION',
  },
  consultAction: {
    zh: '预约定制此专属方案',
    en: 'Consult on this portfolio',
  },
};

export const caseStoriesContent = {
  eyebrow: {
    zh: '真实案例场景',
    en: 'CASE SCENARIOS',
  },
  imageAlt: {
    zh: '案例场景配图',
    en: 'Case Scenario Illustration',
  },
  feedbackLabel: 'Verified Client Feedbacks',
  timelineJournalTitle: 'WT VIP WHITE-GLOVE SERVICE JOURNAL',
};

export const plannerContent = {
  defaultDestination: '广东 (Guangdong)',
  serviceTypes: [
    { id: 'health', label: { zh: '体检陪同', en: 'Companion' } },
    { id: 'travel', label: { zh: '家庭定制游', en: 'Travel' } },
    { id: 'roots', label: { zh: '文化寻根', en: 'Roots' } },
  ],
  urgencyOptions: [
    { id: 'fast', label: { zh: '近期急需 (48h内对接)', en: 'Immediate (Within 48h)' } },
    { id: 'plan', label: { zh: '规划未来 (配合假期)', en: 'Future Vacation Planner' } },
  ],
  destinationNote: {
    zh: '· 拒绝普通土特产代理',
    en: '· Pure Custom Service Only',
  },
  destinations: [
    { value: '广东 (Guangdong)', label: { zh: '广东 (珠三角及潮汕侨乡)', en: 'Guangdong Province' } },
    { value: '福建 (Fujian)', label: { zh: '福建 (闽南祖籍与岩茶文化源地)', en: 'Fujian Province' } },
    { value: '云南 (Yunnan)', label: { zh: '云南 (滇南高原与多民族非遗体验)', en: 'Yunnan Province' } },
    { value: '四川 (Sichuan)', label: { zh: '四川 (巴蜀山水与亲子慢行)', en: 'Sichuan Province' } },
    { value: '新疆 (Xinjiang)', label: { zh: '新疆 (西域人文历史与壮丽丝路)', en: 'Xinjiang Region' } },
    { value: '青海 (Qinghai)', label: { zh: '青海 (高原生态与多代慢行)', en: 'Qinghai Province' } },
    { value: '浙江 (Zhejiang)', label: { zh: '浙江 (江南水乡与宗祠寻根)', en: 'Zhejiang Province' } },
    { value: '奥克兰 (Auckland)', label: { zh: '奥克兰总部 (新西兰纯净高奢定制)', en: 'Auckland (Pure Luxury Travel)' } },
  ],
  addons: [
    { id: 'bilingual', label: { zh: '中英双语顾问', en: 'Bilingual Advisor' }, resultLabel: { zh: '中英双语顾问', en: 'Bilingual Support' } },
    { id: 'medical', label: { zh: '体检现场陪同', en: 'Checkup Companion' }, resultLabel: { zh: '体检现场陪同', en: 'Checkup Companion' } },
    { id: 'documentary', label: { zh: '随行纪录片拍摄', en: 'Homecoming Film Crew' }, resultLabel: { zh: '随行纪录片', en: 'Custom Film Crew' } },
    { id: 'access', label: { zh: '轮椅/无障碍动线', en: 'Barrier-free Mapping' }, resultLabel: { zh: '无障碍动线', en: 'Accessibility Mapping' } },
  ],
  calculating: {
    zh: '正在匹配服务团队...',
    en: 'Optimizing resources...',
  },
  confirmed: 'CONFIRMED',
  operationalSector: {
    zh: '目标服务区',
    en: 'OPERATIONAL SECTOR',
  },
  timelineStrategy: {
    zh: '时效响应',
    en: 'TIMELINE STRATEGY',
  },
  selectedPrivileges: {
    zh: '已选附加服务',
    en: 'EXCLUSIVE SERVICES SELECTED',
  },
  checkSymbol: '✓',
  commitmentIcon: '⚠️',
  commitmentTitle: {
    zh: 'WT 服务边界说明',
    en: 'WT SERVICE SCOPE NOTE',
  },
  commitmentText: {
    zh: 'WT 提供旅行、陪同、翻译沟通、资料整理与行程协调服务，不提供医疗诊断、治疗建议或医疗结果承诺。所有医学判断应以持牌医疗机构及医生意见为准。',
    en: 'WT provides travel, companion, translation, document organization, and itinerary coordination services. We do not provide medical diagnosis, treatment advice, or medical outcome guarantees. Medical judgments should come from licensed providers.',
  },
};

export const processContent = {
  eyebrow: {
    zh: '尊享定制流程',
    en: 'HOW IT WORKS',
  },
  qualityStandard: {
    zh: 'WT 白手套服务标准',
    en: 'WT ROYAL SERVICE STEP',
  },
  milestoneHeading: {
    zh: '核心任务与成果交付物 :',
    en: 'CORE MILESTONES & OUTPUTS :',
  },
  checkSymbol: '✓',
  checklists: [
    {
      zh: ['注册海外专属管家账户', '专属Zoom视频需求分析会', '收集行程偏好、体检预约需求、寻根地名等'],
      en: ['Create global account', 'Dedicated Zoom video intake session', 'Consolidate travel, appointment, or clan records'],
    },
    {
      zh: ['服务顾问整理体检陪同需求', '文史顾问梳理迁徙线索', '定制慢节奏路线草图'],
      en: ['Service advisors organize companion needs', 'Researchers analyze heritage clues', 'Slow itineraries and accessibility layouts drafted'],
    },
    {
      zh: ['协助确认预约或地方资源', '实地核验酒店与动线', '确认地方联络人'],
      en: ['Confirm appointments or local resources', 'Audit hotel and route accessibility', 'Confirm local liaison'],
    },
    {
      zh: ['专车点对点接送', '专业人员现场陪同', '重要时刻影像记录'],
      en: ['Point-to-point private transfers', 'Professional on-site companion support', 'Media capture for important moments'],
    },
    {
      zh: ['交付双语资料总结', '整理影像与档案', '支持后续沟通'],
      en: ['Deliver bilingual document summaries', 'Organize media and records', 'Support follow-up communication'],
    },
  ],
};

export const contactSectionContent = {
  eyebrow: {
    zh: '新西兰总部受托服务',
    en: 'NZ SERVICE COORDINATION',
  },
  guarantees: [
    {
      title: { zh: '24小时极速响应', en: '24-Hour Active Response' },
      desc: { zh: '新西兰奥克兰总部与中国服务团队无缝对接，首问责任制', en: 'Seamless dual coordination by Auckland HQ and China service teams' },
    },
    {
      title: { zh: '1对1资深定制顾问', en: 'Personal Custom Director' },
      desc: { zh: '指派十年以上高端文旅、接待或跨国服务背景项目顾问提供服务', en: 'Senior project advisor with 10+ years in premium travel, hospitality, or cross-border service' },
    },
    {
      title: { zh: '隐私与资料保护', en: 'Privacy-Conscious Coordination' },
      desc: { zh: '重视家庭资料、行程信息和个人隐私，按服务所需范围进行沟通与整理', en: 'We treat family details, itinerary information, and personal records with care and limited-purpose handling' },
    },
  ],
  placeholders: {
    name: { zh: '例如：张先生', en: 'e.g., Prof. Zhang' },
    messenger: 'WeChat ID / WhatsApp / Telegram',
    email: 'name@domain.com',
    phone: '+64 21 000 0000',
    details: {
      zh: '例：我定居在奥克兰，父母在广州天河区。希望安排回国体检陪同、接送和资料翻译整理，预计今年10月回国探亲...',
      en: 'e.g., Based in Wellington, parents in Hangzhou. Seeking checkup companion support, transfers, and document organization...',
    },
  },
  categories: [
    { value: 'health', label: { zh: '回国体检陪同与行程协助', en: 'Homecoming Checkup Companion & Travel Assistance' } },
    { value: 'travel', label: { zh: '多代同堂高端定制慢旅行', en: 'Custom Multi-Generational Travel' } },
    { value: 'roots', label: { zh: '华裔新生代谱系考证与返乡寻根', en: 'Roots-Seeking & Ancestral Heritage Search' } },
    { value: 'multi', label: { zh: '多项联合定制服务规划', en: 'Comprehensive Joint Custom Portfolios' } },
  ],
  successMeta: {
    ticketId: { zh: '受理号', en: 'TICKET ID' },
    intakeZone: { zh: '时区归属', en: 'INTAKE ZONE' },
    intakeValue: 'Auckland / Wellington',
    securityLine: {
      zh: '安全连接 · 家庭资料谨慎处理',
      en: 'SECURE PIPELINE · PRIVACY-CONSCIOUS HANDLING',
    },
  },
};

export const footerContent = {
  brandDescription: {
    zh: '新西兰注册公司：WT NEW ZEALAND CULTURAL EXCHANGE & TOURISM LIMITED，致力于架设连接全球华裔家庭与中国文化、旅行及生活协助资源的信任桥梁。',
    en: 'Registered in NZ: WT NEW ZEALAND CULTURAL EXCHANGE & TOURISM LIMITED. Dedicated to bridging diaspora families with trusted travel, cultural, and family-assistance resources.',
  },
  certification: 'NZ TOURISM CERTIFIED',
  directoryTitle: {
    zh: '服务地图',
    en: 'DIRECTORY',
  },
  hubsTitle: {
    zh: '全球接待中心与联络方式',
    en: 'GLOBAL HUBS & CONTACT',
  },
  aucklandHub: {
    zh: '奥克兰总部 (HQ)',
    en: 'Auckland HQ',
  },
  chinaHub: {
    zh: '中国南方办事处',
    en: 'Southern China Hub',
  },
  emailLabel: {
    zh: '客服邮箱：',
    en: 'Email: ',
  },
  wechatLabel: {
    zh: '微信号：',
    en: 'WeChat ID: ',
  },
  copyrightNotice: {
    zh: `版权所有：WT 新西兰文化交流与旅游有限公司 | 新西兰注册号：${contactInfo.nzRegistration} | 粤ICP备 8910234号-1`,
    en: `NZ Registration No: ${contactInfo.nzRegistration} | Privacy & NDA Compliances Certified by NZ-Gvt Guidelines.`,
  },
  ndaTerms: {
    zh: '保密协议条款',
    en: 'NDA Terms',
  },
  medicalDisclaimer: {
    zh: '服务边界说明',
    en: 'Service Scope Note',
  },
};

export const wechatContactContent = {
  title: {
    zh: '微信扫码 · 即刻对接',
    en: 'WECHAT OFFICIAL CHAT',
  },
  scanLabel: {
    zh: '扫二维码，添加我为朋友',
    en: 'Scan to Add Me as Friend',
  },
  wechatIdLabel: {
    zh: `微信客服号：${contactInfo.wechatId}`,
    en: `WeChat ID: ${contactInfo.wechatId}`,
  },
  emailHeading: {
    zh: '官方联系人邮箱',
    en: 'CONTACT EMAIL',
  },
  copyTitle: 'Copy Email',
  copied: {
    zh: '已复制',
    en: 'COPIED',
  },
  copy: {
    zh: '复制',
    en: 'COPY',
  },
  aucklandPhoneLabel: {
    zh: '新西兰奥克兰总部',
    en: 'Auckland HQ Phone',
  },
  chinaPhoneLabel: {
    zh: '中国南方办事处',
    en: 'China Hub Phone',
  },
};
